const studentDemographics = [
    {
        "effective_term": "202310",
        "status_code": "AS",
        "level_code": "UG",
        "student_type_code": "C",
        "matric_term": null,
        "admit_term": "201910",
        "admit_code": "ED",
        "expected_graduation_date": "26-MAY-2024",
        "campus_code": null,
        "classification": "08",
        "academic_standing": null,
        "rate_code": "EUSTD",
        "time_status_code": null,
        "time_status_term": null,
        "oim_active_ind": null,
        "residency_code": "S",
        "college_code": "UG",
        "degree_code": "AB",
        "major_code": "MIDE",
        "program": "AB_MID_EST",
        "intended_graduation_term": "202310",
        "intended_academic_graduation_year": "2023",
        "department_code": "MES",
        "catalog_term": "201910",
        "leave_code": null,
        "leave_from_date": null,
        "leave_to_date": null,
        "activity_date": "31-MAY-2023",
        "data_origin": "Banner",
        "user_id": "CBEATTIE",
        "pidm": 1382482,
        "brown_id": "140103676",
        "workday_id": "634233",
        "iso_number": "6009550001651316",
        "auth_id": "mkessle1",
        "banner_id": "B01327085",
        "amcas_id": null,
        "person_title": null,
        "last_name": "Kessler",
        "first_name": "Mara",
        "middle_initial": null,
        "legal_name_suffix": null,
        "pref_first_name": null,
        "pref_last_name": null,
        "chosen_full_name": null,
        "dob": "07-DEC-2000",
        "sex": "F",
        "pronouns": null,
        "confid_ind": "N",
        "death_ind": "N",
        "death_date": null,
        "ethn_code": "T",
        "ethn_desc": "Race/Ethnicity Other",
        "hispanic_ind": "N",
        "race": "White",
        "relg_code": null,
        "relg_desc": null,
        "marital_code": null,
        "marital_desc": null,
        "citizenship_code": "Y",
        "citizenship_desc": "US Citizen",
        "is_citizen": "Y",
        "student_visa_type": null,
        "birth_nation_intl": null,
        "birth_city_intl": null,
        "legal_nation_intl": null,
        "legal_city_intl": null,
        "applicant_ind": "Y",
        "student_ind": "Y",
        "faculty_ind": "N",
        "advisor_ind": "N",
        "alum_ind": "N",
        "addresses": [
            {
                "pidm": 1382482,
                "brown_id": "140103676",
                "banner_id": "B01327085",
                "workday_id": "634233",
                "address_type": "PO",
                "start_date": "14-JUN-2019",
                "street1": "Brown University",
                "street2": "Box 5858",
                "street3": null,
                "city": "Providence",
                "state_code": "RI",
                "zip_code": "02912",
                "county_code": null,
                "nation_code": null,
                "nation": null,
                "activity_date": "14-JUN-2019"
            },
            {
                "pidm": 1382482,
                "brown_id": "140103676",
                "banner_id": "B01327085",
                "workday_id": "634233",
                "address_type": "LO",
                "start_date": "14-SEP-2023",
                "street1": "14 Young Orchard",
                "street2": "Apt 2",
                "street3": null,
                "city": "Providence",
                "state_code": "RI",
                "zip_code": "02906",
                "county_code": null,
                "nation_code": null,
                "nation": null,
                "activity_date": "14-SEP-2023"
            }
        ],
        "emailAddresses": [],
        "phoneNumbers": [],
        "emergencyContactInfo": [],
        "cohorts": [],
        "priorNames": []
    },
    {
        "effective_term": "202310",
        "status_code": "AS",
        "level_code": "UG",
        "student_type_code": "F",
        "matric_term": null,
        "admit_term": "202310",
        "admit_code": "RD",
        "expected_graduation_date": "30-MAY-2027",
        "campus_code": null,
        "classification": "01",
        "academic_standing": null,
        "rate_code": "EUSTD",
        "time_status_code": null,
        "time_status_term": null,
        "oim_active_ind": null,
        "residency_code": "C",
        "college_code": "UG",
        "degree_code": "BH",
        "major_code": "ENGN",
        "program": "BACHELORS",
        "intended_graduation_term": "202620",
        "intended_academic_graduation_year": "2026",
        "department_code": "ENGN",
        "catalog_term": "202310",
        "leave_code": null,
        "leave_from_date": null,
        "leave_to_date": null,
        "activity_date": "28-JUN-2023",
        "data_origin": "BATCHUPDATE",
        "user_id": "PRDJOB",
        "pidm": 1814244,
        "brown_id": "140437546",
        "workday_id": "651965",
        "iso_number": "6009550001930587",
        "auth_id": "fchrist2",
        "banner_id": "B01758844",
        "amcas_id": null,
        "person_title": null,
        "last_name": "Christianson",
        "first_name": "Finnur",
        "middle_initial": "T",
        "legal_name_suffix": null,
        "pref_first_name": null,
        "pref_last_name": null,
        "chosen_full_name": null,
        "dob": "17-APR-2003",
        "sex": "M",
        "pronouns": null,
        "confid_ind": "N",
        "death_ind": "N",
        "death_date": null,
        "ethn_code": "T",
        "ethn_desc": "Race/Ethnicity Other",
        "hispanic_ind": "N",
        "race": "White",
        "relg_code": null,
        "relg_desc": null,
        "marital_code": null,
        "marital_desc": null,
        "citizenship_code": "Y",
        "citizenship_desc": "US Citizen",
        "is_citizen": "Y",
        "student_visa_type": null,
        "birth_nation_intl": null,
        "birth_city_intl": null,
        "legal_nation_intl": null,
        "legal_city_intl": null,
        "applicant_ind": "Y",
        "student_ind": "Y",
        "faculty_ind": "N",
        "advisor_ind": "N",
        "alum_ind": "N",
        "addresses": [
            {
                "pidm": 1814244,
                "brown_id": "140437546",
                "banner_id": "B01758844",
                "workday_id": "651965",
                "address_type": "PO",
                "start_date": "28-JUL-2023",
                "street1": "Brown University",
                "street2": "Box 3063",
                "street3": null,
                "city": "Providence",
                "state_code": "RI",
                "zip_code": "02912",
                "county_code": null,
                "nation_code": null,
                "nation": null,
                "activity_date": "28-JUL-2023"
            }
        ],
        "emailAddresses": [],
        "phoneNumbers": [],
        "emergencyContactInfo": [],
        "cohorts": [],
        "priorNames": []
    },
    {
        "effective_term": "202310",
        "status_code": "AS",
        "level_code": "UG",
        "student_type_code": "0",
        "matric_term": null,
        "admit_term": "202310",
        "admit_code": null,
        "expected_graduation_date": null,
        "campus_code": null,
        "classification": "SP",
        "academic_standing": null,
        "rate_code": "EUNOT",
        "time_status_code": null,
        "time_status_term": null,
        "oim_active_ind": null,
        "residency_code": "0",
        "college_code": "UG",
        "degree_code": "000000",
        "major_code": "0000",
        "program": "SPEC_STU_UG",
        "intended_graduation_term": null,
        "intended_academic_graduation_year": null,
        "department_code": "0000",
        "catalog_term": "202310",
        "leave_code": null,
        "leave_from_date": null,
        "leave_to_date": null,
        "activity_date": "14-SEP-2023",
        "data_origin": "Banner",
        "user_id": "DOSOLOMO",
        "pidm": 1814375,
        "brown_id": "140437384",
        "workday_id": null,
        "iso_number": "6009550002468066",
        "auth_id": "hjang22",
        "banner_id": "B01758975",
        "amcas_id": null,
        "person_title": null,
        "last_name": "Jang",
        "first_name": "Hyun Seok",
        "middle_initial": null,
        "legal_name_suffix": null,
        "pref_first_name": null,
        "pref_last_name": null,
        "chosen_full_name": null,
        "dob": "09-AUG-2003",
        "sex": "M",
        "pronouns": null,
        "confid_ind": "N",
        "death_ind": "N",
        "death_date": null,
        "ethn_code": "T",
        "ethn_desc": "Race/Ethnicity Other",
        "hispanic_ind": "N",
        "race": "Asian",
        "relg_code": null,
        "relg_desc": null,
        "marital_code": null,
        "marital_desc": null,
        "citizenship_code": "PR",
        "citizenship_desc": "Permanent Resident of the US",
        "is_citizen": "Y",
        "student_visa_type": "F1",
        "birth_nation_intl": null,
        "birth_city_intl": null,
        "legal_nation_intl": "KS",
        "legal_city_intl": "Rep of Korea",
        "applicant_ind": "Y",
        "student_ind": "Y",
        "faculty_ind": "N",
        "advisor_ind": "N",
        "alum_ind": "N",
        "addresses": [],
        "emailAddresses": [],
        "phoneNumbers": [],
        "emergencyContactInfo": [],
        "cohorts": [],
        "priorNames": []
    }
]

const studentAddresses = [
    {
        "pidm": 1382482,
        "brown_id": "140103676",
        "banner_id": "B01327085",
        "workday_id": "634233",
        "address_type": "PO",
        "start_date": "14-JUN-2019",
        "street1": "Brown University",
        "street2": "Box 5858",
        "street3": null,
        "city": "Providence",
        "state_code": "RI",
        "zip_code": "02912",
        "county_code": null,
        "nation_code": null,
        "nation": null,
        "activity_date": "14-JUN-2019"
    },
    {
        "pidm": 1814244,
        "brown_id": "140437546",
        "banner_id": "B01758844",
        "workday_id": "651965",
        "address_type": "PO",
        "start_date": "28-JUL-2023",
        "street1": "Brown University",
        "street2": "Box 3063",
        "street3": null,
        "city": "Providence",
        "state_code": "RI",
        "zip_code": "02912",
        "county_code": null,
        "nation_code": null,
        "nation": null,
        "activity_date": "28-JUL-2023"
    },
    {
        "pidm": 1583081,
        "brown_id": "140186055",
        "banner_id": "B01527684",
        "workday_id": "629124",
        "address_type": "PO",
        "start_date": "09-FEB-2023",
        "street1": "Brown University",
        "street2": "Box 5061",
        "street3": null,
        "city": "Providence",
        "state_code": "RI",
        "zip_code": "02912",
        "county_code": null,
        "nation_code": null,
        "nation": null,
        "activity_date": "09-FEB-2023"
    }
]

for (let i = 0; i < studentAddresses.length; i++) {
    console.log(`RECORD ${i}`)
    try {
        if (studentDemographics[i].banner_id === studentAddresses[i].banner_id) {
            console.log("banner_id match: " + studentDemographics[i].banner_id)
        } else {
            console.log(`banner_id DOES NOT match. \n\tDemographic: ${studentDemographics[i].banner_id}, \n\tAddresses: ${studentAddresses[i].banner_id}`)
        }
    } catch (TypeError) {
        console.log("ERROR missing information");
    }

    try {
        if (studentDemographics[i].addresses[i].address_type === "PO" || studentDemographics[0].addresses[0].address_type === "LO") {
            console.log("Address match: " + studentDemographics[i].addresses[i].address_type)
        } else {
            console.log("Address DOES NOT match, it is listed as: " + studentDemographics[i].addresses[i].address_type)
        }
    } catch (error) {
        console.error("ERROR No property of address_type exists.");
    }

    console.log("")
}


